@extends('layouts.family')
@section('title','عشيرة الزعبي — السلط')
@section('content')
<section class="family-hero"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-7"><span class="status-badge light-badge"><i class="bi bi-archive"></i> أرشيف عائلي رقمي</span><p class="family-kicker"><i class="bi bi-geo-alt"></i> {{ $family['location'] }}</p><h1>{{ $family['name'] }}</h1><p class="lead">{{ $family['summary'] }}</p><div class="d-flex flex-wrap gap-2"><a class="btn btn-gold btn-lg" href="{{ route('family.tree') }}">استكشف الشجرة الجامعة</a><a class="btn btn-outline-light btn-lg" href="{{ route('family.history') }}">اقرأ تاريخ العشيرة</a></div></div><div class="col-lg-5"><div class="family-tree-art"><span>الزعبي</span><div class="genealogy-orbit"><i class="bi bi-tree-fill"></i></div></div></div></div></div></section>
<section class="quick-links"><div class="container"><div class="quick-grid">@foreach([['family.tree','diagram-3','الشجرة الجامعة'],['family.history','hourglass-split','التاريخ'],['family.branches','bezier2','الأفخاذ والفروع'],['family.archive','archive','الأرشيف'],['family.people','person-badge','الشخصيات'],['family.members','people','دليل الأبناء']] as [$route,$icon,$label])<a href="{{ route($route) }}"><i class="bi bi-{{ $icon }}"></i><span>{{ $label }}</span></a>@endforeach</div></div></section>
<section class="section-space"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-6"><span class="eyebrow">هوية تجمع النسب والمكان</span><h2 class="section-title">جذور في ذاكرة السلط</h2><p class="section-lead">{{ $family['identity'] }}</p></div><div class="col-lg-6"><div class="notice-card"><i class="bi bi-people"></i><div><h3>التماسك والاستمرارية</h3><p>{{ implode(' • ', $family['values']) }}</p></div></div></div></div></div></section>
<section class="section-space surface"><div class="container"><div class="document-feature"><div class="document-year">{{ $history['document']['year'] }}</div><div><span class="status-badge verified">مصدر تاريخي منشور</span><h2>{{ $history['document']['title'] }}</h2><p>{{ $history['document']['summary'] }}</p><small>المصدر: {{ $history['document']['source'] }}</small></div></div></div></section>
<section class="section-space"><div class="container"><div class="section-heading"><span class="eyebrow">الفروع المتاحة حالياً في الأرشيف الرقمي</span><h2 class="section-title">الأفخاذ والفروع الموثقة حالياً</h2></div><div class="branch-preview mt-4">@foreach($branches as $branch)<a href="{{ url('/al-zoubi/branches/'.$branch['slug']) }}"><strong>{{ $branch['name'] }}</strong>@if($branch['children'])<small>{{ implode('، ', array_column($branch['children'],'name')) }}</small>@else<small>{{ $branch['status'] }}</small>@endif<i class="bi bi-arrow-left"></i></a>@endforeach</div><a class="btn btn-outline-primary mt-4" href="{{ route('family.branches') }}">استكشف الأفخاذ والفروع</a></div></section>
<section class="section-space surface"><div class="container"><div class="row g-5"><div class="col-lg-5"><span class="eyebrow">جذر واحد، نوافذ متعددة</span><h2 class="section-title">الشجرة الجامعة</h2><p>{{ $genealogy['note'] }}</p><a class="btn btn-primary" href="{{ route('family.tree') }}">عرض الشجرة الجامعة</a></div><div class="col-lg-7"><div class="lineage-preview">@foreach(array_slice($genealogy['shared_lineage_preview'],-4) as $name)<span>{{ $name }}</span>@if(!$loop->last)<i class="bi bi-arrow-down"></i>@endif @endforeach<div class="lineage-branches">@foreach($branches as $branch)<b>{{ $branch['name'] }}</b>@endforeach</div></div></div></div></div></section>
<section class="section-space"><div class="container"><div class="row g-4"><div class="col-lg-6"><span class="eyebrow">ذاكرة تاريخية</span><h2 class="section-title">جذور وحضور في السلط</h2><p>{{ $history['overview'] }}</p><a class="btn btn-outline-primary" href="{{ route('family.history') }}">اقرأ تاريخ العشيرة</a></div><div class="col-lg-6"><span class="eyebrow">من الأرشيف</span><div class="row g-3">@foreach(array_slice($archive,0,4) as $item)<div class="col-6"><div class="value-card"><i class="bi bi-{{ $item['icon'] }}"></i><h3>{{ $item['title'] }}</h3><p>{{ $item['type'] }}</p></div></div>@endforeach</div></div></div></div></section>
<section class="section-space surface"><div class="container"><span class="eyebrow">زعبي السلط فقط</span><h2 class="section-title">شخصيات من أبناء العشيرة</h2><div class="row g-3 mt-2">@foreach(array_slice($people,0,3) as $person)<div class="col-md-4"><div class="value-card"><h3>{{ $person['name'] }}</h3><p class="text-primary">{{ $person['title'] }}</p><p>{{ $person['connection'] }}</p></div></div>@endforeach</div><a class="btn btn-primary mt-4" href="{{ route('family.people') }}">عرض الشخصيات الموثقة</a></div></section>
@endsection
