@extends('layouts.family')
@section('title','عشيرة الزعبي')
@section('content')
<section class="family-hero"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-7"><span class="status-badge light-badge"><i class="bi bi-info-circle"></i> محتوى تعريفي تجريبي وغير معتمد نسبيًا</span><p class="family-kicker"><i class="bi bi-geo-alt"></i> السلط — الأردن</p><h1>عشيرة الزعبي</h1><p class="lead">مساحة رقمية تجمع الشجرة الجامعة وتاريخ العشيرة وأرشيفها وفروعها، وتصل أبناءها عبر الأجيال.</p><div class="d-flex flex-wrap gap-2"><a class="btn btn-gold btn-lg" href="{{ route('family.tree') }}">استكشف الشجرة الجامعة</a><a class="btn btn-outline-light btn-lg" href="{{ route('family.history') }}">تعرّف على تاريخ العشيرة</a></div></div><div class="col-lg-5"><div class="family-tree-art"><span>الزعبي</span><div class="genealogy-orbit"><i class="bi bi-tree-fill"></i></div></div></div></div></div></section>
<section class="quick-links"><div class="container"><div class="quick-grid">@foreach([['family.tree','diagram-3','الشجرة الجامعة'],['family.history','hourglass-split','التاريخ'],['family.branches','bezier2','الأفخاذ والفروع'],['family.archive','archive','الأرشيف'],['family.achievements','award','الإنجازات'],['family.people','person-badge','الشخصيات'],['family.members','people','دليل الأبناء']] as [$route,$icon,$label])<a href="{{ route($route) }}"><i class="bi bi-{{ $icon }}"></i><span>{{ $label }}</span><i class="bi bi-arrow-left short-arrow"></i></a>@endforeach</div></div></section>
<section class="section-space"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-5"><span class="eyebrow">عن العشيرة</span><h2 class="section-title">ذاكرة تتّسع لكل جيل</h2><p class="section-lead">هذه نبذة توضيحية تبيّن موضع المحتوى التعريفي مستقبلًا. لا تمثل المعلومات المعروضة هنا مرجعًا تاريخيًا أو إثباتًا للنسب قبل اعتمادها من مصادر موثوقة.</p></div><div class="col-lg-7"><div class="notice-card"><i class="bi bi-patch-question"></i><div><h3>المراجعة قبل النشر</h3><p>سترتبط الروايات والأسماء والفروع بالمصادر وحالة التحقق بوضوح، ليظل المحتوى العائلي أمينًا ودقيقًا.</p></div></div></div></div></div></section>
<section class="section-space surface"><div class="container"><div class="section-heading d-flex justify-content-between align-items-end"><div><span class="eyebrow">بنية توضيحية</span><h2 class="section-title">الفروع الرئيسية</h2><p class="section-lead">أسماء العرض أدناه غير مكتملة ولا تمثل حصرًا أو اعتمادًا للأنساب.</p></div><a class="btn btn-outline-primary d-none d-md-block" href="{{ route('family.branches') }}">عرض جميع الأفخاذ والفروع</a></div><div class="branch-preview mt-4">@foreach(['العودات','القواسمة','الرحايمة','الخليفات','الجمعات'] as $name)<a href="{{ $loop->first ? route('family.branches.show') : route('family.branches') }}"><span>{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><strong>{{ $name }}</strong><small>اسم تجريبي للمراجعة</small><i class="bi bi-arrow-left"></i></a>@endforeach</div><a class="btn btn-outline-primary w-100 mt-3 d-md-none" href="{{ route('family.branches') }}">عرض جميع الفروع</a></div></section>
<section class="section-space"><div class="container"><div class="row g-5"><div class="col-lg-5"><span class="eyebrow">سرد موثّق مستقبلًا</span><h2 class="section-title">محطات من تاريخ العشيرة</h2><p class="section-lead">بنية زمنية توضيحية فقط، دون تواريخ أو ادعاءات تاريخية فعلية.</p><a class="btn btn-outline-primary" href="{{ route('family.history') }}">قراءة تاريخ العشيرة</a></div><div class="col-lg-7"><x-timeline-item label="مرحلة توضيحية" title="الجذور والروايات" description="موضع مخصص للروايات بعد مراجعتها وربطها بمصادرها."/><x-timeline-item label="مرحلة توضيحية" title="الاستقرار والانتشار" description="سياق جغرافي سيُكتب فقط اعتمادًا على مراجع موثوقة."/><x-timeline-item label="الحاضر" title="حفظ الذاكرة" description="جمع الشهادات والمواد الأرشيفية في سجل عائلي منظم."/></div></div></div></section>
<section class="section-space surface"><div class="container"><div class="section-heading"><span class="eyebrow">مختارات تجريبية</span><h2 class="section-title">من الأرشيف</h2></div><div class="row g-3 mt-3">@foreach([['صور قديمة','image'],['وثائق','file-earmark-text'],['مخطوطات','journal-richtext'],['مقابلات','mic'],['كتب','book'],['خرائط','map']] as [$title,$icon])<div class="col-6 col-lg-2"><x-archive-card :title="$title" :type="$title" :icon="$icon" /></div>@endforeach</div><div class="text-center mt-4"><a class="btn btn-primary" href="{{ route('family.archive') }}">استكشف الأرشيف</a></div></div></section>
<section class="section-space"><div class="container"><div class="row g-4"><div class="col-lg-6"><div class="feature-panel"><i class="bi bi-award"></i><span class="eyebrow">أثر وعطاء</span><h2>إنجازات العشيرة وأبنائها</h2><p>مساحة لإبراز الإنجازات الموثقة أكاديميًا ومهنيًا ومجتمعيًا.</p><a href="{{ route('family.achievements') }}">جميع الإنجازات <i class="bi bi-arrow-left"></i></a></div></div><div class="col-lg-6"><div class="feature-panel people-panel"><i class="bi bi-person-badge"></i><span class="eyebrow">سِيَر مختارة</span><h2>أبرز الشخصيات</h2><p>ملفات تعريفية تراعي الدقة والسياق ومصادر المعلومات.</p><a href="{{ route('family.people') }}">عرض أبرز الشخصيات <i class="bi bi-arrow-left"></i></a></div></div></div></div></section>
<section class="pb-5"><div class="container"><div class="directory-cta"><i class="bi bi-people-fill"></i><div><span>دليل عائلي يحترم الخصوصية</span><h2>تواصل مع أبناء العشيرة</h2><p>اكتشف الملفات العامة مستقبلًا حسب المجال والمهنة والمنصب والمنطقة، دون نشر بيانات اتصال حساسة.</p></div><a class="btn btn-gold" href="{{ route('family.members') }}">استكشف دليل أبناء العشيرة</a></div></div></section>
@endsection
