@extends('layouts.app')
@section('title','الرئيسية')
@section('content')
<section class="hero platform-hero"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-7"><span class="eyebrow">منصة الذاكرة العائلية العربية</span><h1 class="hero-title">نحفظ الجذور...<br><span>ونربط الأجيال</span></h1><p class="hero-copy">تاريخ العائلة ليس مجرد أسماء، بل إرث يستحق أن يبقى. جذور منصة رقمية لحفظ الأنساب وتوثيق التاريخ وأرشفة الصور والوثائق والإنجازات.</p><div class="d-flex flex-wrap gap-2"><a class="btn btn-primary btn-lg" href="{{ route('family.home') }}">استكشف عشيرة الزعبي <i class="bi bi-arrow-left"></i></a><a class="btn btn-outline-primary btn-lg" href="#about">تعرّف على جذور</a></div><div class="trust-row mt-4"><span><i class="bi bi-shield-check"></i> خصوصية مدروسة</span><span><i class="bi bi-journal-check"></i> مصادر واضحة</span><span><i class="bi bi-people"></i> ذاكرة مشتركة</span></div></div><div class="col-lg-5"><div class="heritage-art"><i class="bi bi-tree-fill tree-symbol"></i><div class="heritage-caption"><strong>شجرة واحدة، وذاكرة حيّة</strong><span>لكل عائلة مساحتها المستقلة داخل جذور.</span></div></div></div></div></div></section>
<section class="section-space" id="families"><div class="container"><div class="section-heading"><span class="eyebrow">المساحات العائلية</span><h2 class="section-title">العشائر المتاحة على جذور</h2><p class="section-lead">نبدأ بمساحة عائلية واحدة مصممة لتجمع الشجرة والتاريخ والأرشيف ضمن تجربة مستقلة.</p></div><article class="featured-family mt-4"><div class="family-emblem"><i class="bi bi-diagram-3-fill"></i></div><div class="flex-grow-1"><span class="status-badge">المساحة المتاحة حاليًا</span><h3>عشيرة الزعبي</h3><p><i class="bi bi-geo-alt"></i> السلط — الأردن</p><p class="text-muted mb-0">موقع عائلي تجريبي متكامل لاستكشاف الشجرة الجامعة والفروع والذاكرة الأرشيفية.</p></div><div><a class="btn btn-gold" href="{{ route('family.home') }}">دخول موقع العشيرة <i class="bi bi-arrow-left"></i></a><small class="d-block text-center mt-2 text-muted">المزيد من العائلات قريبًا</small></div></article></div></section>
<section class="section-space surface" id="about"><div class="container"><div class="text-center mx-auto section-heading"><span class="eyebrow">ما الذي نحفظه؟</span><h2 class="section-title">كل ما يصنع ذاكرة العائلة</h2></div><div class="row g-3 mt-3">@foreach([['diagram-3','شجرة العائلة'],['hourglass-split','تاريخ العائلة'],['images','الصور والوثائق'],['award','الإنجازات'],['person-badge','الشخصيات'],['people','دليل أبناء العائلة']] as [$icon,$title])<div class="col-6 col-lg-4"><div class="value-card"><span class="feature-icon"><i class="bi bi-{{ $icon }}"></i></span><h3>{{ $title }}</h3><p>مساحة منظمة تحفظ المحتوى في سياقه وتجعله سهل الاستكشاف.</p></div></div>@endforeach</div></div></section>
<section class="section-space"><div class="container"><div class="archive-story"><div><span class="eyebrow text-white">ذاكرة لا تضيع</span><h2>الأرشيف العائلي الرقمي</h2><p>نجمع الصور القديمة والوثائق والمخطوطات والروايات العائلية والسجلات التاريخية ومصادر الأنساب في أرشيف هادئ ومنظّم.</p><div class="archive-tags">@foreach(['صور قديمة','وثائق','مخطوطات','قصص عائلية','سجلات','مصادر'] as $tag)<span>{{ $tag }}</span>@endforeach</div></div><i class="bi bi-archive archive-story-icon"></i></div></div></section>
<section class="pb-5"><div class="container"><div class="vision-panel text-center"><span class="eyebrow">رؤية جذور</span><h2 class="section-title">من الجذور... نصنع المستقبل</h2><p>حين تُحفظ الذاكرة بعناية، تصبح صلةً بين من سبق ومن سيأتي؛ منصة تستقبل عائلات أكثر في المستقبل، بمساحات تحترم خصوصية كل عائلة وهويتها.</p></div></div></section>
@endsection
