@extends('layouts.app')
@section('title','الرئيسية')
@section('content')
<section class="hero"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-7"><span class="eyebrow">أرشيف عائلي عربي معاصر</span><h1 class="hero-title mb-3">تاريخ عائلتك<br><span>يستحق أن يُحفظ</span></h1><p class="hero-copy mb-4">جذور منصة رقمية لتوثيق الأنساب، وحفظ تاريخ العائلات، وربط الأجيال في شجرة عائلية موثقة وسهلة الاستكشاف.</p><div class="search-panel mb-4"><i class="bi bi-search align-self-center me-2 text-muted"></i><input class="form-control" aria-label="ابحث عن عائلة أو شخص" placeholder="ابحث عن عائلة، شخص، أو منطقة..."><button class="btn btn-primary px-4">بحث</button></div><div class="trust-row"><span><i class="bi bi-shield-check"></i> خصوصية مدروسة</span><span><i class="bi bi-journal-check"></i> مصادر وتوثيق</span><span><i class="bi bi-people"></i> مساهمة عائلية</span></div></div><div class="col-lg-5"><div class="heritage-art"><i class="bi bi-tree-fill tree-symbol"></i><div class="heritage-caption"><strong class="d-block fs-5">ذاكرة حيّة لا مجرد أسماء</strong><span class="small opacity-75">شجرة، وثائق، صور، وروايات تحفظ سياق العائلة.</span></div></div></div></div></div></section>
<section class="section-space"><div class="container"><div class="d-flex flex-wrap justify-content-between align-items-end mb-4"><div><span class="eyebrow">شجرات مقترحة</span><h2 class="section-title mb-1">استكشف عائلات من المنطقة</h2><p class="section-lead mb-0">نماذج عرض توضّح كيف تستضيف جذور شجرات مستقلة لعائلات متعددة.</p></div><a class="btn btn-outline-primary" href="/families">عرض جميع العائلات</a></div><div class="row g-4"><div class="col-md-6 col-lg-4"><x-family-card name="عشيرة الزعبي" location="السلط، الأردن" people="2,450" branches="18" href="/families/al-zoubi" /></div><div class="col-md-6 col-lg-4"><x-family-card name="عائلة الحسين" location="عمّان، الأردن" people="1,320" branches="9" tone="sage" /></div><div class="col-md-6 col-lg-4"><x-family-card name="آل الخطيب" location="إربد، الأردن" people="980" branches="6" tone="gold" /></div></div></div></section>
<section class="section-space surface" id="about"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-5"><span class="eyebrow">كل شيء في سياقه</span><h2 class="section-title">منصة للذاكرة العائلية، وليست رسمًا للشجرة فقط</h2><p class="section-lead">اجمع العلاقات والمصادر والصور والحكايات في سجل واضح، مع تمييز المعلومة الموثقة عن الرواية العائلية.</p></div><div class="col-lg-7"><div class="row g-3"><div class="col-sm-6"><div class="stat-card"><span class="feature-icon mb-3"><i class="bi bi-diagram-3"></i></span><h3 class="h6 fw-bold">شجرة جامعة</h3><p class="small text-muted mb-0">فروع متعددة ضمن سجل عائلي واحد دون تكرار الأشخاص.</p></div></div><div class="col-sm-6"><div class="stat-card"><span class="feature-icon mb-3"><i class="bi bi-archive"></i></span><h3 class="h6 fw-bold">أرشيف منظم</h3><p class="small text-muted mb-0">مكان للصور والوثائق والمقابلات والمراجع.</p></div></div><div class="col-sm-6"><div class="stat-card"><span class="feature-icon mb-3"><i class="bi bi-patch-check"></i></span><h3 class="h6 fw-bold">توثيق واضح</h3><p class="small text-muted mb-0">حالات مرئية تساعد القارئ على فهم درجة الثقة.</p></div></div><div class="col-sm-6"><div class="stat-card"><span class="feature-icon mb-3"><i class="bi bi-lock"></i></span><h3 class="h6 fw-bold">احترام الخصوصية</h3><p class="small text-muted mb-0">تصميم يراعي حساسية بيانات الأشخاص الأحياء.</p></div></div></div></div></div></div></section>
<section class="section-space"><div class="container"><div class="text-center mb-5"><span class="eyebrow">ثلاث خطوات بسيطة</span><h2 class="section-title">كيف تعمل جذور؟</h2></div><div class="row g-4 text-center">@foreach([['1','أنشئ مساحة العائلة','ابدأ بهوية واضحة ووصف موجز لعائلتك.'],['2','ابنِ الشجرة ووثّقها','أضف الأشخاص والفروع واربط كل معلومة بمصدرها.'],['3','شارك الذاكرة','ادعُ أفراد العائلة للمساهمة وفق قواعد واضحة.']] as $step)<div class="col-md-4"><div class="stat-card"><div class="display-6 fw-bold text-warning mb-2">{{ $step[0] }}</div><h3 class="h5 fw-bold">{{ $step[1] }}</h3><p class="text-muted mb-0">{{ $step[2] }}</p></div></div>@endforeach</div></div></section>
<section class="section-space surface" id="archive"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-6"><span class="eyebrow">الأرشيف العائلي</span><h2 class="section-title">احفظ الدليل بجانب الحكاية</h2><p class="section-lead">الصور القديمة، وثائق الميلاد، الرسائل، والكتب ليست مرفقات هامشية؛ إنها ما يمنح الذاكرة سياقها ويجعلها قابلة للفهم عبر الأجيال.</p><a class="btn btn-outline-primary" href="#">تعرّف على المكتبة</a></div><div class="col-lg-6"><div class="row g-3"><div class="col-6"><x-source-card title="سجل عائلي قديم" type="وثيقة عائلية" date="حوالي 1928" /></div><div class="col-6"><x-source-card title="صورة تجمع عائلي" type="صورة مؤرشفة" date="1950" /></div></div></div></div></div></section>
<section class="py-5"><div class="container"><div class="cta d-lg-flex align-items-center justify-content-between"><div><h2 class="h2 fw-bold">ابدأ حفظ ذاكرة عائلتك اليوم</h2><p class="mb-lg-0 opacity-75">أنشئ شجرة منظمة يمكن لعائلتك أن تكملها معًا.</p></div><button class="btn btn-gold btn-lg">إنشاء شجرة عائلية</button></div></div></section>
@endsection
