@extends('layouts.app')
@section('title','دليل الواجهة')
@section('content')
<x-page-header title="نظام تصميم جذور" eyebrow="UI Playground" description="مرجع حي للمكوّنات والألوان وحالات الواجهة العربية." />
<section class="section-space"><div class="container"><h2 class="h4 fw-bold mb-3">الألوان</h2><div class="row g-2 mb-5">@foreach([['أساسي','#163F32','primary',''],['ثانوي','#2E6755','secondary',''],['ذهبي','#B78A43','gold',''],['رملي','#F5F1E8','background','light'],['ورقي','#FFFDF8','surface','light'],['حبر','#202823','text','']] as $color)<div class="col-6 col-md-4 col-lg-2"><div class="swatch swatch-{{ $color[2] }} {{ $color[3] }}"><strong>{{ $color[0] }}</strong><br>{{ $color[1] }}</div></div>@endforeach</div>
<div class="row g-5"><div class="col-lg-6"><h2 class="h4 fw-bold">العناوين والنصوص</h2><h1>عنوان رئيسي</h1><h2>عنوان قسم</h2><h3>عنوان فرعي</h3><p>نص عربي مريح للقراءة يوضح التسلسل البصري والمسافات المناسبة.</p><p class="text-muted">نص ثانوي للمعلومات المساندة.</p><h2 class="h4 fw-bold mt-5">الأزرار والحالات</h2><div class="d-flex flex-wrap gap-2"><button class="btn btn-primary">زر أساسي</button><button class="btn btn-outline-primary">زر بإطار</button><button class="btn btn-gold">زر ذهبي</button><span class="status-badge">موثق</span><span class="status-badge unverified">غير موثق</span></div></div><div class="col-lg-6"><h2 class="h4 fw-bold">حقول الإدخال</h2><label class="form-label" for="demo-name">الاسم الكامل</label><input id="demo-name" class="form-control mb-3" placeholder="أدخل الاسم"><label class="form-label" for="demo-select">المنطقة</label><select id="demo-select" class="form-select mb-3"><option>اختر المنطقة</option></select><div class="search-panel"><input class="form-control" placeholder="ابحث في الشجرة"><button class="btn btn-primary">بحث</button></div><div class="alert alert-warning mt-3"><i class="bi bi-info-circle"></i> المعلومات غير الموثقة تُعرض بوضوح للمستخدم.</div></div></div>
<hr class="my-5"><h2 class="h4 fw-bold mb-3">مكوّنات المنتج</h2><div class="row g-4"><div class="col-md-6 col-lg-4"><x-family-card name="عائلة نموذجية" location="السلط، الأردن" people="420" branches="6" /></div><div class="col-md-6 col-lg-4"><x-branch-card name="فرع سالم" description="وصف موجز لفرع ضمن الشجرة الجامعة." people="85" subbranches="3" /></div><div class="col-md-6 col-lg-4"><x-person-card name="أحمد محمود" years="1950–2020" /></div><div class="col-md-6"><x-stat-card icon="people" value="2,450" label="شخصًا في الشجرة" /></div><div class="col-md-6"><x-source-card title="سجل عائلي قديم" type="وثيقة" date="1928" /></div></div>
<h2 class="h4 fw-bold mt-5">التبويبات ومسار الصفحة</h2><nav><ol class="breadcrumb"><li class="breadcrumb-item">الرئيسية</li><li class="breadcrumb-item">العائلات</li><li class="breadcrumb-item active">عائلة نموذجية</li></ol></nav><ul class="nav family-tabs mb-4"><li><button class="nav-link active">نبذة</button></li><li><button class="nav-link">الفروع</button></li><li><button class="nav-link">الأرشيف</button></li></ul><x-empty-state title="لا توجد مساهمات بعد" description="ستظهر المساهمات المعتمدة في هذا القسم." />
<div class="d-flex justify-content-center mt-4"><ul class="pagination"><li class="page-item active"><span class="page-link">1</span></li><li class="page-item"><a class="page-link" href="#">2</a></li><li class="page-item"><a class="page-link" href="#">التالي</a></li></ul></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#demoModal">فتح نافذة نموذجية</button></div></section>
<div class="modal fade" id="demoModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5">تأكيد الإجراء</h2><button class="btn-close ms-0 me-auto" data-bs-dismiss="modal"></button></div><div class="modal-body">هذه نافذة توضح أسلوب الحوارات في جذور.</div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal">إلغاء</button><button class="btn btn-primary">تأكيد</button></div></div></div></div>
@endsection
